services:
  backend:
    build: ./backend
    command: python3 /usr/src/app/backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
